name: Maven build / deploy

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: mvn clean test -Pdebug -B -U -Dgpg.skip -Dmaven.javadoc.skip=true
      - name: Deploy with Maven to GitHub packages
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: mvn deploy --settings .maven.xml -B -U -Pgithub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Create release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          name: ${{ github.ref }}
          draft: true
          prerelease: false
          files: |
            player/target/librespot-player-*.jar
            api/target/librespot-api-*.jar